
//
//  Data.swift
//  KBTUApp
//
//  Created by User on 09.03.2021.
//  Copyright © 2021 User. All rights reserved.
//

import Foundation
var images:[String] = ["ded.png","meetingRector.jpg","olimp2021.jpg","stipendialnayaPrograma.png","bestTeacher.jpg"]
var labels:[String] = ["СУЛЕЙМЕНОВ ЭСЕН НУРГАЛИЕВИЧ: ПОЧЕТНОЕ ЗВАНИЕ «ОСНОВАТЕЛЬ НАУЧНОГО НАПРАВЛЕНИЯ»","On February 6, 2021, was held the first face-to-face meeting of the KBTU Rector with the Board of the KBTU ALUMNI Association.","Dear students and college graduates! We are pleased to announce to you the holding of the KBTU","Scientific and educational foundation named after Academician Shakhmardan Yessenov","Teachers of KBTU Isakhov Asylbek Abdiashimovich and Kulpeshov Beibut Shaiykovich became the holders of the title The best teacher of the"]
var text:[String] = ["Решением Президиума Российской Академии Естествознания научному руководителю исследований по грантовому финансированию, главному научному сотруднику Научно-образовательного центра матриаловедения и проблем коррозии Сулейменову Эсену Нургалиевичу присвоено Почетное звание «Основатель научного направления». \n Президиум Российской Академии Естествознания (РАЕ) поздравляет Вас и желает дальнейших успехов в развитии Отечественной науки и плодотворной работы в области образования и развития созданного Вами нового научного направления! Новое научное направление – это фундаментальное исследование, в процессе реализации которого эффективно решаются новые и ранее не решенные крупные задачи в определенной отрасли науки, - говорится в сообщении. \n Поздравляем!",
                     "On February 6, 2021, was held the first face-to-face meeting of the KBTU Rector with the Board of the KBTU ALUMNI Association. \n Within the framework of the meeting, took place an extensive tour of laboratories and pavilions (Huawei, Emerson, Halyk Bank, Honeywell, etc.), visits to dean's offices and the opening of the office of the Alumni Association. /n In addition to the graduates who came from the cities of Nur-Sultan, Aktau, Shymkent, Aktobe, there were participants in the online format from such countries as Norway, Russia, and Singapore. The Rector of KBTU Ibrashev Kenzhebek Niyazovich spoke about the achievements of the University in last years, plans for the medium-term period, as well as support for the creation of the Association and the need for close cooperation. \n  «The doors of the university are always open for our graduates. The creation of the Council of the Association will give a new impetus to the interaction of KBTU, its students and graduates to achieve common goals», - Kenzhebek Niyazovich said in his welcoming speech.\n On the part of the graduates, the President of the Association Dyusembayev Medet, together with the heads of the directions, told about the goals and work plans of the Council of the Association, about already implemented projects, including: \n - launch of the Mentoring program; \n - launch of a social program for talented university students; \n  - creating a single platform for graduates and students; \n  - development of the KBTU startup ecosystem; \n - creating a page in the social network facebook; \n - opening of the Leadership School for KBTU girls; \n  - international cooperation and much more. \n   «Each of us today in the walls of KBTU again felt a continuous connection with his native alma mater. We already have more than 6,000 graduates, qualified specialists who work in many countries of the world, and I am sure that we will be able to involve even more active and not indifferent to the fate of the university in the work of the Association», - Medet summed up his speech. \n  KBTU management supported the Association's Work Plan and expressed readiness to provide any necessary support in its joint implementation. \n  «The Council of the Association has gathered a strong team of active and creative graduates, with whom we have already divided into committees, started implementing specific projects and will use the best international practices of the ALUMNI communities», - said Ekaterina Smolyakova, Vice - Rector for Organizational and Educational Work, coordinator of the Alumni Association project from the university. \n  Several graduates have expressed a desire to create and start funding a scholarship program for students from graduates. Moreover, some of the graduates who participated in the event expressed their willingness to make the first contribution to the Endowment Fund for a substantial amount.",
                     "Dear students and college graduates! We are pleased to announce to you the holding of the KBTU Republican Subject Olympiad among among students in grades 10-12 and college graduates! (citizens of the Republic of Kazakhstan). \n The Olympiad will be held in five areas: \n - Information and communication technologies \n - Business and management \n - Manufacturing and processing industries \n - Marine transport and technology \n - Chemical engineering and processes. \n The winners of the Olympiad will receive GRANTS and DISCOUNTS for studying at KBTU! \n Format: Online \n Round 1: March 11, 2021 \n Round 2: March 17, 2021 \n You can read the terms and conditions in the Olympiad Regulations. \n Registration is available at the link \n  Registration will be open until March 7, 2021 at 23:59 \n  Telegram group for Olympiad participants",
                     "Scientific and educational foundation named after Academician Shakhmardan Yessenov announces a competition for the provision of 17 monthly student scholarships for 27,000 tenge. \n Participants of the program: students, citizens of Kazakhstan over 18 years old, studying at Kazakh universities for 2-3 courses of bachelor's degree or 1st year of master's degree and 1st year of internship in natural science, technical, medical and IT specialties. \n Number of grants: 17 \n To participate in the Competition for the Sh. Yessenov scholarship, a candidate must: \n 1. Fill in an online application on the Foundation's website - yessenovfoundation.org \n 2. Attach to the application: \n Mandatory documents: \n  1. Scan of the identity card; \n   2. Essay on the topic “What have I done and will do for the science of Kazakhstan? What is important to you and why?  (the appeal can be provided only in writing); \n 3. Student transcript (GPA not lower than 3.0), applications with a score lower than 3.0 are not considered; \n    4. A copy of the diploma of higher education for graduate students (bachelor, specialist). \n   Additional documents: \n   5. Scientific certificates / diplomas - no more than 2 certificates*; \n   6. Certificates for social activity and volunteering - no more than 3 certificates*; \n    7. Publication - no more than 2 publications*;","Teachers of KBTU Isakhov Asylbek Abdiashimovich and Kulpeshov Beibut Shaiykovich became the holders of the title “The best teacher of the university 2020”! \n  623 applicants from 73 higher educational institutions of the republic took part in the competition. The activities of teachers were assessed according to the updated qualitative and quantitative indicators of assessing the work of applicants, consisting of two blocks: I block - the quality of teaching, II block - research activities. \n  For the first time this year, in order to exclude subjectivity, applications for participation in the competition “The best teacher of the university-2020”, the procedure for checking documents, as well as an appeal, were carried out through the information system of the MES RoK online. \n   Isakhov Asylbek Abdiashimovich and Kulpeshov Beibut Shaiykovich are professors of the Scientific and Educational Center of Mathematics and Cybernetics of KBTU. In addition to professorship, Asylbek Isakhov holds the position of dean of this faculty. \n  Congratulations!"]

var items:[String] = ["Faculty of Geology and Geological Exploration"," Faculty of Energy and Oil & Gas Industry","Faculty of Information Technologies","Faculty of General Education","Business School","International School of Economics","Kazakhstan Maritime Academy"," School of Mathematics and Cybernetics"," School of Chemical Engineering"]
var facultyIcons:[String] = ["geology.png","oil.png","it.png","general.png","bs.png","ibs.png","maritime.png","math.png","energy.png"]
