
//
//  Data.swift
//  KBTUApp
//
//  Created by User on 09.03.2021.
//  Copyright © 2021 User. All rights reserved.
//

import Foundation
var images:[String] = ["ded.png","meetingRector.jpg","olimp2021.jpg","stipendialnayaPrograma.png","bestTeacher.jpg"]
var labels:[String] = ["СУЛЕЙМЕНОВ ЭСЕН НУРГАЛИЕВИЧ: ПОЧЕТНОЕ ЗВАНИЕ «ОСНОВАТЕЛЬ НАУЧНОГО НАПРАВЛЕНИЯ»","On February 6, 2021, was held the first face-to-face meeting of the KBTU Rector with the Board of the KBTU ALUMNI Association.","Dear students and college graduates! We are pleased to announce to you the holding of the KBTU","Scientific and educational foundation named after Academician Shakhmardan Yessenov","Teachers of KBTU Isakhov Asylbek Abdiashimovich and Kulpeshov Beibut Shaiykovich became the holders of the title The best teacher of the"]
var text:[String] = ["Решением Президиума Российской Академии Естествознания научному руководителю исследований по грантовому финансированию, главному научному сотруднику Научно-образовательного центра матриаловедения и проблем коррозии Сулейменову Эсену Нургалиевичу присвоено Почетное звание «Основатель научного направления». \n Президиум Российской Академии Естествознания (РАЕ) поздравляет Вас и желает дальнейших успехов в развитии Отечественной науки и плодотворной работы в области образования и развития созданного Вами нового научного направления! Новое научное направление – это фундаментальное исследование, в процессе реализации которого эффективно решаются новые и ранее не решенные крупные задачи в определенной отрасли науки, - говорится в сообщении. \n Поздравляем!",
                     "On February 6, 2021, was held the first face-to-face meeting of the KBTU Rector with the Board of the KBTU ALUMNI Association. \n Within the framework of the meeting, took place an extensive tour of laboratories and pavilions (Huawei, Emerson, Halyk Bank, Honeywell, etc.), visits to dean's offices and the opening of the office of the Alumni Association. /n In addition to the graduates who came from the cities of Nur-Sultan, Aktau, Shymkent, Aktobe, there were participants in the online format from such countries as Norway, Russia, and Singapore. The Rector of KBTU Ibrashev Kenzhebek Niyazovich spoke about the achievements of the University in last years, plans for the medium-term period, as well as support for the creation of the Association and the need for close cooperation. \n  «The doors of the university are always open for our graduates. The creation of the Council of the Association will give a new impetus to the interaction of KBTU, its students and graduates to achieve common goals», - Kenzhebek Niyazovich said in his welcoming speech.\n On the part of the graduates, the President of the Association Dyusembayev Medet, together with the heads of the directions, told about the goals and work plans of the Council of the Association, about already implemented projects, including: \n - launch of the Mentoring program; \n - launch of a social program for talented university students; \n  - creating a single platform for graduates and students; \n  - development of the KBTU startup ecosystem; \n - creating a page in the social network facebook; \n - opening of the Leadership School for KBTU girls; \n  - international cooperation and much more. \n   «Each of us today in the walls of KBTU again felt a continuous connection with his native alma mater. We already have more than 6,000 graduates, qualified specialists who work in many countries of the world, and I am sure that we will be able to involve even more active and not indifferent to the fate of the university in the work of the Association», - Medet summed up his speech. \n  KBTU management supported the Association's Work Plan and expressed readiness to provide any necessary support in its joint implementation. \n  «The Council of the Association has gathered a strong team of active and creative graduates, with whom we have already divided into committees, started implementing specific projects and will use the best international practices of the ALUMNI communities», - said Ekaterina Smolyakova, Vice - Rector for Organizational and Educational Work, coordinator of the Alumni Association project from the university. \n  Several graduates have expressed a desire to create and start funding a scholarship program for students from graduates. Moreover, some of the graduates who participated in the event expressed their willingness to make the first contribution to the Endowment Fund for a substantial amount.",
                     "Dear students and college graduates! We are pleased to announce to you the holding of the KBTU Republican Subject Olympiad among among students in grades 10-12 and college graduates! (citizens of the Republic of Kazakhstan). \n The Olympiad will be held in five areas: \n - Information and communication technologies \n - Business and management \n - Manufacturing and processing industries \n - Marine transport and technology \n - Chemical engineering and processes. \n The winners of the Olympiad will receive GRANTS and DISCOUNTS for studying at KBTU! \n Format: Online \n Round 1: March 11, 2021 \n Round 2: March 17, 2021 \n You can read the terms and conditions in the Olympiad Regulations. \n Registration is available at the link \n  Registration will be open until March 7, 2021 at 23:59 \n  Telegram group for Olympiad participants",
                     "Scientific and educational foundation named after Academician Shakhmardan Yessenov announces a competition for the provision of 17 monthly student scholarships for 27,000 tenge. \n Participants of the program: students, citizens of Kazakhstan over 18 years old, studying at Kazakh universities for 2-3 courses of bachelor's degree or 1st year of master's degree and 1st year of internship in natural science, technical, medical and IT specialties. \n Number of grants: 17 \n To participate in the Competition for the Sh. Yessenov scholarship, a candidate must: \n 1. Fill in an online application on the Foundation's website - yessenovfoundation.org \n 2. Attach to the application: \n Mandatory documents: \n  1. Scan of the identity card; \n   2. Essay on the topic “What have I done and will do for the science of Kazakhstan? What is important to you and why?  (the appeal can be provided only in writing); \n 3. Student transcript (GPA not lower than 3.0), applications with a score lower than 3.0 are not considered; \n    4. A copy of the diploma of higher education for graduate students (bachelor, specialist). \n   Additional documents: \n   5. Scientific certificates / diplomas - no more than 2 certificates*; \n   6. Certificates for social activity and volunteering - no more than 3 certificates*; \n    7. Publication - no more than 2 publications*;","Teachers of KBTU Isakhov Asylbek Abdiashimovich and Kulpeshov Beibut Shaiykovich became the holders of the title “The best teacher of the university 2020”! \n  623 applicants from 73 higher educational institutions of the republic took part in the competition. The activities of teachers were assessed according to the updated qualitative and quantitative indicators of assessing the work of applicants, consisting of two blocks: I block - the quality of teaching, II block - research activities. \n  For the first time this year, in order to exclude subjectivity, applications for participation in the competition “The best teacher of the university-2020”, the procedure for checking documents, as well as an appeal, were carried out through the information system of the MES RoK online. \n   Isakhov Asylbek Abdiashimovich and Kulpeshov Beibut Shaiykovich are professors of the Scientific and Educational Center of Mathematics and Cybernetics of KBTU. In addition to professorship, Asylbek Isakhov holds the position of dean of this faculty. \n  Congratulations!"]

var facultiesTitle:[String] = ["Faculty of Geology and Geological Exploration"," Faculty of Energy and Oil & Gas Industry","Faculty of Information Technologies","Faculty of General Education","Business School","International School of Economics","Kazakhstan Maritime Academy"," School of Mathematics and Cybernetics"," School of Chemical Engineering"]
var facultyIcons:[String] = ["geology","oil","it","general","bs","ibs","maritime","math","chemistry"]
var deans:[String]=["geologyDean","oilDean","itDean","generalDean","bsDean","ibsDean","maritimeDean","mathDean","chemistryDean"]
var deanTexts=["The faculty trains specialists in the field of geological survey, prospecting, and exploration of mineral deposits that meet the requirements of the modern market and international standards. Training is carried out at two levels – bachelor's and master's degrees in Geology and exploration of mineral deposits. ",
               "Dear applicants! \n The oil and gas industry plays a leading role in the economy of our country. Kazakhstan is included in the list of top countries where large reserves of hydrocarbons are available, developed and produced. Therefore, the oil and gas sector of the country’s economy always needs highly qualified specialists.",
               "Dear friends, colleagues, applicants, parents, graduates, and visitors! \n The Faculty of Information Technology (FIT) was established 17 years ago,  now, it is the largest Faculty of the Kazakh-British Technical University (KBTU). Thousand of our graduates are working in Kazakhstan and abroad and are connected to the FIT thanks to our very own specialization---Information Technologies. ",
               "Dear Applicant, \n I want to personally welcome you to our General Education Faculty. The faculty lives like a reef colony, united in a pursuit of knowledge on the grounds of which you can move to the chosen goal – gaining the quality professional education more confidently, efficiently and persistently. ",
               "The KBTU Business School has experienced tremendous development since the establishment of the University in 2001. We are proud of who we are today, what values we bring to the society and the development of future leaders of Kazakhstan. Being the leader school in business education in the country, we are continuously upgrading our content and delivery methods. ",
               " International School of Economics is a unique faculty of KBTU that has been a recognized teaching center of the University of London since 2005.  All our students study for the University of London degree under the academic direction of the London School of Economics (LSE). It means that the study materials for each course are developed by one of the top universities in social sciences in the world  ",
               "Dear applicant!\n  Welcome to the Kazakhstan Maritime Academy.\n  The KMA educates and trains young men and women to become internationally recognized qualified navigators and marine engineers. These highly skilled merchant marine professionals can work anywhere in the world, either at sea or on shore.",
               "Welcome to the KBTU School of Mathematics and Cybernetics (SMC)!\n A degree in mathematics and applied mathematics opens doors to solid and successful career because mathematics is the foundation of everything. The SMC is one of the youngest faculties of the KBTU. We are proud of our strong faculty and popular programs. ",
               "Dear prospective students and visitors ! \n It is a pleasure to great everyone interested in the news from the School of Chemical Engineering!  I hope that this insite will benefit you. \n \n \n \n "]
var facultyMoreText = ["Advantages of training in the specialty Geology and exploration of mineral deposits: \n - highly qualified teaching staff; \n -  training with the use of active and innovative methods; \n -  high demand for KBTU graduates in international organizations, enterprises; \n -  the possibility of obtaining a high-paying job both in Kazakhstan and abroad; \n -  the possibility of obtaining a double-degree postgraduate education; \n -   the close relationship with subsoil user companies participating in joint training;",
                       "The faculty also provides an opportunity for graduates of APEC PetroTechnic Graduate College to undergo reduced training and receive a bachelor’s degree. The faculty prepares masters for the educational program “Industrial Project Management and Engineering” under an agreement with Agip Karachaganak B.V. and Eni Corporate University S.p.A. \n Faculty graduates are always in demand in the labor market and meet the needs of employers in the oil and gas industry. \n If you have chosen our educational programs for higher education and as a foundation for your future profession, we believe that you will become a competitive and qualified specialist.\n Together with you, we will achieve high achievements in the main mission of the faculty - training personnel with the necessary knowledge and competencies in the oil and gas industry and educating the future generation of the country.\n Best regards,\n Dean of the Faculty of Energy and Oil and Gas Industry \n Yerdos Ongarbayev.",
                       "The FIT teaches to learn, it teaches to be responsible, trying together with the student to pave the way for the success of the latter. And I would like everyone who consciously chooses us as the foundation, the beginning of their future career to know it. The simple motto is - if you chose FIT, then you must take responsibility. The FIT family will be as useful as possible to you. \n If you know how to take responsibility for yourself, if you understand that only your own concern can be held responsible for your future, if you are sure that the FIT family is a ticket to your future, then spend another 5 minutes reading the links in the message! Enjoy! We wish you great success to the future member of our FIT family! \n  Rasim Suliev \n  Dean FIT",
                       "In the presented information below you can find out more details about the goals and priorities of our faculty.\n I wish you success and high achievements in self-improvement! We are waiting for you in our departments. The teaching staff of the faculty is always glad to communicate with you and is ready to provide you with consultations at any convenient for you time on any issues of your concern.\n Best Regards,\n Dan Besedin",
                       "Being a part of KBTU and having the vision for providing world class education and learning in the heart of Almaty, we are working hard on building the best quality partnerships with our individual and corporate partners both locally and internationally. For example, our students are exposed to international experience through exchange programs such as Erasmus+ and Abay-Verne. Moreover, the KBTU School is accredited by the  prestigious accreditation by the Accreditation Council for Business School and Programs (ACBSP).\n Are you looking for a top notch business school in Kazakhstan? The KBTU Business School is where your needs and expectations are going to be met.\n  With respect, \n Yerzhan Mukashev \n Dean of Business School",
                       "World class faculty members with doctoral degrees from the best universities around the world are there to help you successfully complete your studies in ISE and achieve your goals. Our staff is committed to student success.\n ISE has been a place of outstanding scholarly activities and excellence for many years. We teach our students not only how to study and apply their knowledge but also to be leaders and critical thinkers. Our students are competitive in the global markets which is reflected in their placements both in international companies and top western universities. We are looking for ambitious and hardworking students!",
                       "Kazakhstan Maritime Academy (KMA) at KBTU is the first and the only Kazakhstani higher educational institution that fosters internationally recognized seafarers.\n  Our 4-year undergraduate program is offered to Kazakhstani as well as international applicants. Every year up to 32 cadets are enrolled for granted places at the KMA. The study language is English for the whole duration of the program.\n State of the art simulators from leading global supplier Kongsberg are provided for practical classes and simulated training. During the course the cadets study in the Netherlands and Kazakhstan. Experienced Dutch lecturers from the largest maritime university in the Netherlands, the STC-Group from Rotterdam, conduct training in marine disciplines and share their rich experience with our students. In the third year of their studies at the KMA, each cadet must spend 12-month at sea. This mandatory apprenticeship is part of international requirements (STCW Convention).",
                       "At KBTU, we believe in integrated teaching and learning approach and offer interdisciplinary learning programs. As a student, you will have the opportunity to study both the basic and elective courses at the SMC and also at the other schools of the KBTU. This interdisciplinary education will diversify your knowledge and learning experience. Moreover, the acquired knowledge and the desire for continuous self-improvement will help you to adapt in future work, since in the future universal specialists will be more in demand. \n Assylbek Issakhov",
                       "Not so much time has passed since the Department of Chemical Engineering was established, but we already have made significant progress. And most importantly, these are our graduates who successfully work in large national and foreign companies: KazMunaiGas, TengizChevroil, NCOC, Petrofac (UAE), Atyrau Oil Refining, Schlumberger, Karachaganak Petroleum Operating, Medherant (British Pharmaceutical Company), as well as continuing their studies for master's and PhD degree in the world front universities: Warwick University (Great Britain), Tokyo Institute of Technology (Japan), KTH Royal Institute of Technology (Sweden), etc. \n  All those who believe in their strength and intellect, make the most daring plans and want to be in demand in the field of chemical engineering, we invite you to join us!\n  I wish you well-being, loyal friends, success in your studies, perseverance in achieving your goals and just good luck! /n   Professor Jamansariyeva Kalykyz Utemissovna,/n Head of the School of Chemical Engineering"]
var favorites: [Faculty] = []

var faculties = [Faculty.init(icon: facultyIcons[0], title: facultiesTitle[0]),
                 Faculty.init(icon: facultyIcons[1], title: facultiesTitle[1]),
                 Faculty.init(icon: facultyIcons[2], title: facultiesTitle[2]),
                 Faculty.init(icon: facultyIcons[3], title: facultiesTitle[3]),
                 Faculty.init(icon: facultyIcons[4], title: facultiesTitle[4]),
                 Faculty.init(icon: facultyIcons[5], title: facultiesTitle[5]),
                 Faculty.init(icon: facultyIcons[6], title: facultiesTitle[6]),
                 Faculty.init(icon: facultyIcons[7], title: facultiesTitle[7]),
                 Faculty.init(icon: facultyIcons[8], title: facultiesTitle[8])]


class Faculty: Equatable{
    static func == (lhs: Faculty, rhs: Faculty) -> Bool {
        return lhs.facultyTitle==rhs.facultyTitle
    }
    
    var facultyIcon: String?
    var facultyTitle:String?
    
    init(icon: String?, title: String?){
        self.facultyIcon = icon
        self.facultyTitle = title
    }
}
